export const rawSchema = {
    id: 2,
    name: "a",
    objectTypeCode: "MEDIA_PLAN",
    workspaceId: 2,
    schemaDetails: [
      {
        id: 28,
        schemaId: 2,
        objectDefinitionId: 37,
        isReadOnly: false,
        objectDefinition: {
          id: 37,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "mediaPlanUnitPrices",
          fieldPath: ".mediaPlanUnitPrices.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 29,
        schemaId: 2,
        objectDefinitionId: 38,
        isReadOnly: false,
        objectDefinition: {
          id: 38,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "id",
          fieldPath: ".mediaPlanUnitPrices.id.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 30,
        schemaId: 2,
        objectDefinitionId: 39,
        isReadOnly: false,
        objectDefinition: {
          id: 39,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "type",
          fieldPath: ".mediaPlanUnitPrices.type.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 31,
        schemaId: 2,
        objectDefinitionId: 40,
        isReadOnly: false,
        objectDefinition: {
          id: 40,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "quantity",
          fieldPath: ".mediaPlanUnitPrices.quantity.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 32,
        schemaId: 2,
        objectDefinitionId: 41,
        isReadOnly: false,
        objectDefinition: {
          id: 41,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "quantityFocPercent",
          fieldPath: ".mediaPlanUnitPrices.quantityFocPercent.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 33,
        schemaId: 2,
        objectDefinitionId: 42,
        isReadOnly: false,
        objectDefinition: {
          id: 42,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "quantityBonus",
          fieldPath: ".mediaPlanUnitPrices.quantityBonus.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 34,
        schemaId: 2,
        objectDefinitionId: 43,
        isReadOnly: false,
        objectDefinition: {
          id: 43,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "priceList",
          fieldPath: ".mediaPlanUnitPrices.priceList.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 35,
        schemaId: 2,
        objectDefinitionId: 44,
        isReadOnly: false,
        objectDefinition: {
          id: 44,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "priceDiscountPercent",
          fieldPath: ".mediaPlanUnitPrices.priceDiscountPercent.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 36,
        schemaId: 2,
        objectDefinitionId: 45,
        isReadOnly: false,
        objectDefinition: {
          id: 45,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "price",
          fieldPath: ".mediaPlanUnitPrices.price.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 37,
        schemaId: 2,
        objectDefinitionId: 46,
        isReadOnly: false,
        objectDefinition: {
          id: 46,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "mediaPlanUnitPriceSuppliers",
          fieldPath: ".mediaPlanUnitPrices.mediaPlanUnitPriceSuppliers.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 38,
        schemaId: 2,
        objectDefinitionId: 47,
        isReadOnly: false,
        objectDefinition: {
          id: 47,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "customerId",
          fieldPath:
            ".mediaPlanUnitPrices.mediaPlanUnitPriceSuppliers.{customerId}.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 39,
        schemaId: 2,
        objectDefinitionId: 48,
        isReadOnly: false,
        objectDefinition: {
          id: 48,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "mediaPlanPayments",
          fieldPath: ".mediaPlanPayments.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 40,
        schemaId: 2,
        objectDefinitionId: 49,
        isReadOnly: false,
        objectDefinition: {
          id: 49,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "mediaPlanApprovals",
          fieldPath: ".mediaPlanApprovals.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 41,
        schemaId: 2,
        objectDefinitionId: 50,
        isReadOnly: false,
        objectDefinition: {
          id: 50,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "customerId",
          fieldPath: ".mediaPlanApprovals.{customerId}.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
      {
        id: 42,
        schemaId: 2,
        objectDefinitionId: 51,
        isReadOnly: false,
        objectDefinition: {
          id: 51,
          objectTypeCode: "MEDIA_PLAN",
          fieldName: "mediaPlanCampaigns",
          fieldPath: ".mediaPlanCampaigns.",
          __typename: "ObjectDefinition",
        },
        __typename: "SchemaDetail",
      },
    ],
    schemaConfigurations: [],
    __typename: "Schema",
  };
  